tools/deploy/cronjob - process must halt on error
If we put it in the condition position, errexit is disabled within
that code path, and errors don't stop the process.  So take it out.

However, we need to make sure that `process` short circuits when
something fails, so conditionally execute the steps in a chain.

diff --git a/tools/deploy/cronjob b/tools/deploy/cronjob
--- a/tools/deploy/cronjob
+++ b/tools/deploy/cronjob
@@ -16,22 +16,31 @@ function logify() {
     "$@" > >(sed -e 's/^/  /') 2> >(sed -e 's/^/  ! /')
 }
 
+# Process one directory (passed as first argument)
+#
+# This should return a non-zero code if any part fails but the other
+# dirs should still be processed (or possibly exit, in the extreme
+# case when all processing should stop)
 function process {
     local dir="${1:?directory argument required}"
     (
-	cd $REPO_DIR/$dir
-	logify $dir bundle install --quiet
-	logify $dir $SEOD download
-	logify $dir $SEOD convert
-	logify $dir $SEOD generate
-	logify $dir sudo -nE $SEOD deploy
+	cd $REPO_DIR/$dir &&
+	logify $dir bundle install --quiet &&
+	logify $dir $SEOD download &&
+	logify $dir $SEOD convert &&
+	logify $dir $SEOD generate &&
+	logify $dir sudo -nE $SEOD deploy &&
 	logify $dir sudo -nE $SEOD triplestore
     )
 }
 
 FAILS=()
+set +o errexit # <- we want to manage failure more finely than this here
+
 for dir in oxford newbridge mersey-green deep-adaptation dotcoop covid-mutual-aid mutual-aid; do
     echo "PROCESSING $dir..."
+
+    
     if process $dir; then
         echo "SUCCEEDED $dir"
     else
